//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpWood.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpWood.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;78&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;18599-2001&quot;
        ///  DocName=&quot;Трубы напорные из полиэтилена. Технические условия&quot;
        ///  DocNameShort=&quot;Труба напорная&quot;
        ///  ShortName=&quot;Труба&quot;
        ///  DocStatus=&quot;True&quot;
        ///  Size=&quot;L&quot;
        ///  MainGroup=&quot;Дерево/Пластмасс&quot;
        ///  Group=&quot;Трубы&quot;
        ///  Image=&quot;Tube&quot;
        ///  HasSteel=&quot;false&quot;
        ///  DimType=&quot;Длина,п.м&quot;
        ///  ItemType1=&quot;Назначение трубы$питьевая$техническая&quot;
        ///  Rule=&quot;[ShortName] ПЭ [Prop1] SDR [Prop2] - [Prop4]x[Prop5] [ItemType1] [DocType] [DocNum]&quot;
        ///  Wd [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_18599_2001 {
            get {
                return ResourceManager.GetString("ГОСТ_18599_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///	Id=&quot;62&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;31938-2012&quot;
        ///	DocName=&quot;Арматура композитная полимерная для армирования бетонных конструкций. Общие технические условия&quot;
        ///	DocNameShort=&quot;Арматура композитная&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;	
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Дерево/Пластмасс&quot;
        ///	Group=&quot;Арматура&quot;
        ///	Image=&quot;&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	WdType=&quot;2,Prop1,L&quot;
        ///	Rule=&quot;[ItemType1]-[Prop1]-[ItemType1]/[ItemType2] - [DocType] [Do [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_31938_2012 {
            get {
                return ResourceManager.GetString("ГОСТ_31938_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;57&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8486-86&quot;
        ///	DocName=&quot;Пиломатериалы хвойных пород&quot;
        ///	DocNameShort=&quot;Брус круглого сечения&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Брус&quot;
        ///	ItemType1=&quot;Материал$хв.$сосна$ель$лиственница$кедр$пихта&quot;
        ///	ItemType2=&quot;Сорт$1$2$3$4&quot;	
        ///	Size=&quot;DxL&quot;
        ///	MainGroup=&quot;Дерево/Пластмасс&quot;
        ///	Group=&quot;Пиломатериалы&quot;
        ///	Image=&quot;Wood_1&quot;
        ///	HasSteel=&quot;false&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName]-[ItemType2]-[ItemType1]-[D]&quot;
        ///  WdType=&quot;2,D,L&quot;
        ///	CMass=&quot;400,400 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8486_86_1 {
            get {
                return ResourceManager.GetString("ГОСТ_8486_86_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;58&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8486-86&quot;
        ///	DocName=&quot;Пиломатериалы хвойных пород&quot;
        ///	DocNameShort=&quot;Брус (Номинальные размеры)&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Брус&quot;
        ///	ItemType1=&quot;Материал$хв.$сосна$ель$лиственница$кедр$пихта&quot;
        ///	ItemType2=&quot;Сорт$1$2$3$4&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Дерево/Пластмасс&quot;
        ///	Group=&quot;Пиломатериалы&quot;
        ///	Image=&quot;Wood_2&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName]-[ItemType2]-[ItemType1]-[Prop1]x[Prop2] [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8486_86_2 {
            get {
                return ResourceManager.GetString("ГОСТ_8486_86_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;59&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8486-86&quot;
        ///	DocName=&quot;Пиломатериалы хвойных пород&quot;
        ///	DocNameShort=&quot;Доска (Номинальные размеры)&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Доска&quot;
        ///	ItemType1=&quot;Материал$хв.$сосна$ель$лиственница$кедр$пихта&quot;
        ///	ItemType2=&quot;Сорт$1$2$3$4&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Дерево/Пластмасс&quot;
        ///	Group=&quot;Пиломатериалы&quot;
        ///	Image=&quot;Wood_2&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName]-[ItemType2]-[ItemType1]-[Prop1]x[Prop [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8486_86_3 {
            get {
                return ResourceManager.GetString("ГОСТ_8486_86_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot;&gt; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///SymbolSum=&quot;7&quot;
        ///Symbol1=&quot;НПВХ&quot; Symbol2=&quot;SDR&quot; Symbol3=&quot;MOP, МПа&quot; Symbol4=&quot;Наружный диаметр (D), мм&quot; Symbol5=&quot;Толщина стенки (t), мм&quot; Symbol6=&quot;Масса 1 м труб, кг&quot; Symbol7=&quot;по ГОСТ&quot;
        ///&gt;
        /// &lt;Item Prop1=&quot;100&quot; Prop2=&quot;41&quot; Prop3=&quot;0,5&quot; Prop4=&quot;63&quot; Prop5=&quot;1,6&quot; Prop6=&quot;0,486&quot; Prop7=&quot;+&quot;/&gt;
        /// &lt;Item Prop1=&quot;100&quot; Prop2=&quot;41&quot; Prop3=&quot;0,5&quot; Prop4=&quot;75&quot; Prop5=&quot;1,9&quot; Prop6=&quot;0,675&quot; Prop7=&quot;+&quot;/&gt;
        /// &lt;Item Prop1=&quot;100&quot; Prop2=&quot;41&quot; Prop3=&quot;0,5&quot; Prop4=&quot;90&quot; Prop5=&quot;2,2&quot; Prop6=&quot;0,945&quot; Prop7=&quot;+&quot;/&gt;
        /// &lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_Р_51613_2000 {
            get {
                return ResourceManager.GetString("ГОСТ_Р_51613_2000", resourceCulture);
            }
        }
    }
}
