//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpOther.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpOther.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;65&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;31360-2007&quot;
        ///  DocName=&quot;Изделия стеновые неармированные из ячеистого бетона автоклавного твердения&quot;
        ///  DocNameShort=&quot;Блоки из ячеистых бетонов&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Блок&quot;
        ///  Size=&quot;LxBxH&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Блоки&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,L,B,H&quot;
        ///  Rule=&quot;[ShortName] [ItemType1]/[L]x[B]x[H]/[ItemType2]/[ItemType3]/[ItemType4] [DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Категория$I$II&quot;
        ///  ItemType2=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_31360_2007_1 {
            get {
                return ResourceManager.GetString("ГОСТ_31360_2007_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;66&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;31360-2007&quot;
        ///  DocName=&quot;Изделия стеновые неармированные из ячеистого бетона автоклавного твердения&quot;
        ///  DocNameShort=&quot;Плиты из ячеистых бетонов&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Плита&quot;
        ///  Size=&quot;LxBxH&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Плиты&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,L,B,H&quot;
        ///  Rule=&quot;[ShortName] [ItemType1]/[L]x[B]x[H]/[ItemType2]/[ItemType3]/[ItemType4] [DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Категория$I$II&quot;
        ///  ItemType2= [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_31360_2007_2 {
            get {
                return ResourceManager.GetString("ГОСТ_31360_2007_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;67&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;379-95&quot;
        ///  DocName=&quot;Кирпич и камни силикатные. Технические условия&quot;
        ///  DocNameShort=&quot;Кирпич и камни силикатные&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Кирпич&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Кирпич/камень&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,Prop2,Prop3,Prop4&quot;
        ///  Rule=&quot;[Prop7] С[Prop6][ItemType3][ItemType4]-[ItemType1]/[ItemType2] [DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Марка по прочности$75$100$125$150$175$200$250$300&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_379_95 {
            get {
                return ResourceManager.GetString("ГОСТ_379_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;68&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;530-2012&quot;
        ///  DocName=&quot;Кирпич и камнь керамические. Общие технические условия&quot;
        ///  DocNameShort=&quot;Кирпич керамический&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Кирпич&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Кирпич/камень&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,Prop2,Prop3,Prop4&quot;
        ///  Rule=&quot;[Prop5]-[ItemType2]-[ItemType1] [Prop2]x[Prop3]x[Prop4]/[Prop6]/[ItemType3]/[ItemType5]/[ItemType4]/[DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Вариант из [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_530_2012_1 {
            get {
                return ResourceManager.GetString("ГОСТ_530_2012_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;69&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;530-2012&quot;
        ///  DocName=&quot;Кирпич и камнь керамические. Общие технические условия&quot;
        ///  DocNameShort=&quot;Камень керамический&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Камень&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Кирпич/камень&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,Prop2,Prop3,Prop4&quot;
        ///  Rule=&quot;[Prop6]-[ItemType2]-[ItemType1] [Prop2]x[Prop3]x[Prop4]/[Prop7]/[ItemType3]/[ItemType5]/[ItemType4]/[DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Вариант из [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_530_2012_2 {
            get {
                return ResourceManager.GetString("ГОСТ_530_2012_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;55&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;539-80&quot;
        ///	DocName=&quot;Трубы и муфты асбестоцементные напорные. Технические условия&quot;
        ///	DocNameShort=&quot;Трубы асбестоцементные&quot;
        ///  DocStatus=&quot;False&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;нет&quot;
        ///	MainGroup=&quot;Прочее&quot;
        ///	Group=&quot;Трубы/муфты&quot;
        ///	Image=&quot;ГОСТ 539-80_1&quot;
        ///	HasSteel=&quot;false&quot;	
        ///	Rule=&quot;[Prop2] [Prop3]x[Prop7] [Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	Symbol1=&quot;Тип трубы&quot; Symbol2=&quot;Класс трубы&quot; Symbol3=&quot;Условный проход&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_539_80_1 {
            get {
                return ResourceManager.GetString("ГОСТ_539_80_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;56&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;539-80&quot;
        ///	DocName=&quot;Трубы и муфты асбестоцементные напорные. Технические условия&quot;
        ///	DocNameShort=&quot;Муфты асбестоцементные&quot;
        ///  DocStatus=&quot;False&quot;
        ///	ShortName=&quot;Муфта&quot;
        ///	Size=&quot;нет&quot;
        ///	MainGroup=&quot;Прочее&quot;
        ///	Group=&quot;Трубы/муфты&quot;
        ///	Image=&quot;ГОСТ 539-80_2&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;false&quot;
        ///	DimType=&quot;нет&quot;
        ///	Rule=&quot;[Prop1] [Prop2] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	Symbol1=&quot;Класс муфты&quot; Symbol2=&quot;Условный проход [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_539_80_2 {
            get {
                return ResourceManager.GetString("ГОСТ_539_80_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;64&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;5742-76&quot;
        ///  DocName=&quot;Изделия из ячеистых бетонов теплоизоляционные&quot;
        ///  DocNameShort=&quot;Изделия из ячеистых бетонов теплоизоляционные&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Теплоизоляционное изделие&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Прочее&quot;
        ///  Group=&quot;Блоки&quot;
        ///  Image=&quot;Blocks&quot;
        ///  OtType=&quot;1,ItemType2,ItemType3,ItemType4&quot;
        ///  Rule=&quot;[ItemType1]-[ItemType2].[ItemType3].[ItemType4]&quot;
        ///  ItemType1=&quot;Марка по плотности$А$Б&quot;
        ///  ItemType1ToolTi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_5742_76 {
            get {
                return ResourceManager.GetString("ГОСТ_5742_76", resourceCulture);
            }
        }
    }
}
