//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpMaterial.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpMaterial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;54&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;26633-2012&quot;
        ///  DocName=&quot;Бетоны тяжелые и мелкозернистые. Технические условия&quot;
        ///  DocNameShort=&quot;Бетоны тяжелые и мелкозернистые&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Бетон&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Материал&quot;
        ///  Group=&quot;Бетоны&quot;
        ///  Image=&quot;&quot;
        ///  CMass=&quot;&quot;
        ///  Rule=&quot;[Бетон кл.][ItemType1][, ][ItemType4][, ][ItemType5]&quot;
        ///  ItemType1=&quot;Класс прочности на сжатие$В3,5$В5$В7,5$В10$В12,5$В15$В20$(B22,5)$В25$(B27,5)$В30$В35$В40$В45$В50 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_26633_2012 {
            get {
                return ResourceManager.GetString("ГОСТ_26633_2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;70&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;28013-98&quot;
        ///  DocName=&quot;Растворы строительные. Общие технические условия&quot;
        ///  DocNameShort=&quot;Растворы строительные&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Раствор&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Материал&quot;
        ///  Group=&quot;Растворы&quot;
        ///  Image=&quot;&quot;
        ///  CMass=&quot;&quot;
        ///  Rule=&quot;[ShortName] [ItemType1][, ][Prop1][, ][ItemType3][, ][ItemType4][, ][ItemType5],[DocType] [DocNum]&quot;
        ///  ItemType1=&quot;Класс по основному назначению$кладочный$облицовочный$штукатурн [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_28013_98 {
            get {
                return ResourceManager.GetString("ГОСТ_28013_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;63&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;8267-93&quot;
        ///  DocName=&quot;Щебень и гравий из плотных горных пород для строительных работ. Технические условия&quot;
        ///  DocNameShort=&quot;Щебень и гравий для строительных работ&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Щебень и гравий&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Материал&quot;
        ///  Group=&quot;Сыпучие материалы&quot;
        ///  Image=&quot;&quot;
        ///  CMass=&quot;&quot;
        ///  Rule=&quot;[ItemType1] [Prop1][,][ItemType2]&quot;
        ///  ItemType1=&quot;Сыпучий материал$Щебень$Гравий&quot;  
        ///  ItemType2=&quot;Марка по мо [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8267_93 {
            get {
                return ResourceManager.GetString("ГОСТ_8267_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;61&quot;
        ///  DocType=&quot;ГОСТ&quot;
        ///  DocNum=&quot;8736-2014&quot;
        ///  DocName=&quot;Песок для строительных работ. Технические условия&quot;
        ///  DocNameShort=&quot;Песок для строительных работ&quot;
        ///  DocStatus=&quot;True&quot;
        ///  ShortName=&quot;Песок&quot;
        ///  Size=&quot;нет&quot;
        ///  MainGroup=&quot;Материал&quot;
        ///  Group=&quot;Сыпучие материалы&quot;
        ///  Image=&quot;&quot;
        ///  CMass=&quot;&quot;
        ///  Rule=&quot;[Песок ][ItemType2][,][ItemType1]&quot;
        ///  ItemType1=&quot;Класс по зерновому составу$класс I$класс II&quot;
        ///  ItemType2=&quot;Группы в зависимости от модуля крупности$повышенной  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8736_2014 {
            get {
                return ResourceManager.GetString("ГОСТ_8736_2014", resourceCulture);
            }
        }
    }
}
