//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpConcrete.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpConcrete.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;1&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;13579-78&quot;
        ///	DocName=&quot;Блоки бетонные для стен подвалов. Технические условия&quot;
        ///	DocNameShort=&quot;Блоки бетонные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Блок&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Блоки&quot;
        ///	Image=&quot;ГОСТ 13579-78&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop10&quot;
        ///	SymbolSum=&quot;10&quot;
        ///	CoType=&quot;1,Prop2,Prop3,Prop4&quot;
        ///	Symbol1=&quot;Марка блока&quot; Symbol2=&quot;L, мм&quot; Symbol3=&quot;B, мм&quot; Symbol4=&quot;H, мм&quot; Symbol5=&quot;Класс бетона&quot;
        ///	Symbol6=&quot;Марка петли&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_13579_78 {
            get {
                return ResourceManager.GetString("ГОСТ_13579_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;2&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8717.0-84&quot;
        ///	DocName=&quot;Ступени железобетонные и бетонные. Технические условия&quot;
        ///	DocNameShort=&quot;Ступени железобетонные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Ступень&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Ступени&quot;
        ///	Image=&quot;ГОСТ 8717.0-84&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop6&quot;
        ///	SymbolSum=&quot;6&quot;
        ///	Symbol1=&quot;Марка ступени&quot; Symbol2=&quot;l, мм&quot; Symbol3=&quot;h, мм&quot; Symbol4=&quot;b, мм&quot; Symbol5=&quot;Бетон, м^3&quot;
        ///	Symbol6=&quot;Масса, кг&quot;
        ///&gt;
        ///  &lt;Item Prop1=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8717_0_84 {
            get {
                return ResourceManager.GetString("ГОСТ_8717_0_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;3&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.011.1-10. Выпуск 1. Часть 1&quot;
        ///	DocName=&quot;Сваи цельные сплошного квадратного сечения с ненапрягаемой арматурой. Рабочие чертежи&quot;
        ///	DocNameShort=&quot;Сваи&quot;
        ///	ShortName=&quot;Свая&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Сваи&quot;
        ///	Image=&quot;Серия 1.011.1-10. Выпуск 1. Часть 1&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop7&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	CoType=&quot;4,Prop2,Prop6,Prop5,60&quot;
        ///	Symbol1=&quot;Марка сваи&quot; Symbol2=&quot;L, мм&quot; Symbol3=&quot;а1, мм&quot;
        ///	Symbol4=&quot;а2, мм [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_011_1_10__Выпуск_1__Часть_1 {
            get {
                return ResourceManager.GetString("Серия_1_011_1_10__Выпуск_1__Часть_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;4&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 1&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 1&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop7&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	CoType=&quot;1,Prop4,Prop5,Prop6&quot;
        ///	Symbol1=&quot;Марка&quot; Symbol2=&quot;Мин.глубина опирания, мм&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_1 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;13&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 10&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые и плитные предварительно напряженные с напрягаемой арматурой класса Ат-V для жилых и общественных зданий со стенами из кирпича толщиной 88 мм&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 10&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_10 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;14&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 11&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые и плитные предварительно напряженные с напрягаемой арматурой класса Ат-IVc для жилых и общественных зданий со стенами из кирпича толщиной 88 мм&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 10&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_11 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;5&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 2&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки плитные для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 2&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop7&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	CoType=&quot;1,Prop4,Prop5,Prop6&quot;
        ///	Symbol1=&quot;Марка&quot; Symbol2=&quot;Мин.глубина опирания, мм&quot; Sy [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_2 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;6&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 3&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки балочные для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 3&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	CoType=&quot;2,Prop4,Prop5,Prop6,130,Prop7&quot;
        ///	Symbol1=&quot;Марка&quot; Symbol2=&quot;Мин.глубина опира [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_3 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;7&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 4&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые для жилых и общественных зданий со стенами из кирпича толщиной 88мм&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 1&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop7&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	CoType=&quot;1,Prop4,Prop5,Prop6&quot;
        ///	Symbol1=&quot;Марка&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_4 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;8&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 5&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки плитные для жилых и общественных зданий со стенами из кирпича толщиной 88 мм&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 2&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop7&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	CoType=&quot;1,Prop4,Prop5,Prop6&quot;
        ///	Symbol1=&quot;Марка&quot;  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_5 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;9&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 6&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки фасадные для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 6&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	CoType=&quot;3,Prop4,Prop5,250,Prop6,130,70&quot;
        ///	Symbol1=&quot;Марка&quot; Symbol2=&quot;Мин.глубина опир [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_6 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;10&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 7&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки фасадные для жилых и общественных зданий со стенами из кирпича толщиной 88 мм&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 7&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	CoType=&quot;3,Prop4,Prop5,250,Prop6,130,90&quot;
        ///	Sym [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_7 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;11&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 8&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые и плитные предварительно напряженные с напрягаемой арматурой класса Ат-V для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 8&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop6&quot;
        ///	SymbolSum=&quot;6&quot;
        ///	CoType=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_8 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;12&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.038.1-1. Выпуск 9&quot;
        ///	DocName=&quot;Перемычки железобетонные для зданий с кирпичными стенами. Перемычки брусковые и плитные предварительно напряженные с напрягаемой арматурой класса Ат-IVс для жилых и общественных зданий&quot;
        ///	DocNameShort=&quot;Перемычки ж/б&quot;
        ///	ShortName=&quot;Перемычка&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Перемычки&quot;
        ///	Image=&quot;Серия 1.038.1-1. Выпуск 8&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;Prop6&quot;
        ///	SymbolSum=&quot;6&quot;
        ///	CoType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_038_1_1__Выпуск_9 {
            get {
                return ResourceManager.GetString("Серия_1_038_1_1__Выпуск_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;15&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.141-1. Выпуск 60&quot;
        ///	DocName=&quot;Панели перекрытий железобетонные многопустотные. Панели с круглыми пустотами длиной 4180,3580,2980,2680 и 2380мм, шириной 1790,1490,1190 и 990мм, армированные стержнями из стали класса A-III и Вр-I&quot;
        ///	DocNameShort=&quot;Многопустотные плиты&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Плита&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Плиты&quot;
        ///	Image=&quot;Серия 1.141-1. Выпуск 60&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	Mass=&quot;P [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_141_1__Выпуск_60 {
            get {
                return ResourceManager.GetString("Серия_1_141_1__Выпуск_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;16&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.141-1. Выпуск 63&quot;
        ///	DocName=&quot;Панели перекрытий железобетонные многопустотные. Панели с круглыми пустотами длиной 6280, 5980, 5680, 5380, 5080 и 4780 мм, шириной 1790, 1490, 1190 и 990 мм, армированные стержнями из стали класса А-V&quot;
        ///	DocNameShort=&quot;Многопустотные плиты&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Плита&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Плиты&quot;
        ///	Image=&quot;Серия 1.141-1. Выпуск 63_1&quot;
        ///	Rule=&quot;[ShortName] [Prop1]&quot;
        ///	M [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_141_1__Выпуск_63_1 {
            get {
                return ResourceManager.GetString("Серия_1_141_1__Выпуск_63_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;17&quot;
        ///	DocType=&quot;Серия&quot;
        ///	DocNum=&quot;1.141-1. Выпуск 63&quot;
        ///	DocName=&quot;Панели перекрытий железобетонные многопустотные. Панели с круглыми пустотами длиной 6280, 5980, 5680, 5380, 5080 и 4780 мм, шириной 1790, 1490, 1190 и 990 мм, армированные стержнями из стали класса А-V&quot;
        ///	DocNameShort=&quot;Многопустотные плиты с усил. торцами&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Плита&quot;
        ///	MainGroup=&quot;Железобетон&quot;
        ///	Group=&quot;Плиты&quot;
        ///	Image=&quot;Серия 1.141-1. Выпуск 63_2&quot;
        ///	Rule=&quot;[ShortNa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Серия_1_141_1__Выпуск_63_2 {
            get {
                return ResourceManager.GetString("Серия_1_141_1__Выпуск_63_2", resourceCulture);
            }
        }
    }
}
