//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mpMetall.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mpMetall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;53&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;103-2006&quot;
        ///	DocName=&quot;Прокат сортовой стальной горячекатанный полосовой. Сортамент&quot;
        ///	DocNameShort=&quot;Полоса&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Полоса&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;List&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1]x[Prop2] [DocType] [DocNum]&quot;
        ///  MeType=&quot;13,Prop1,Prop2,L&quot;
        ///	WMass=&quot;Prop3&quot;
        ///	SymbolSum=&quot;3&quot;
        ///	Symbol1=&quot;Ширина, мм&quot; Symbol2=&quot;Толщина, мм&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_103_2006 {
            get {
                return ResourceManager.GetString("ГОСТ_103_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;52&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;10704-91&quot;
        ///	DocName=&quot;Трубы стальные электросварные прямошевные. Сортамент&quot;
        ///	DocNameShort=&quot;Трубы стальные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Трубы&quot;
        ///	Image=&quot;Tube&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop4&quot;
        ///	SymbolSum=&quot;4&quot;
        ///	MeType=&quot;5,Prop2,Prop3,L&quot;
        ///	Symbol1=&quot;Марка трубы&quot;
        ///	Symbol2=&quot;Наружный диаметр, мм&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_10704_91 {
            get {
                return ResourceManager.GetString("ГОСТ_10704_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;51&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;10884-94&quot;
        ///	DocName=&quot;Сталь арматурная термомеханически упрочненная для железобетонных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматурной стали$Ат400С$Ат500С$Ат600$Ат600С$Ат600К$Ат800$Ат800К$Ат1000$Ат1000К$Ат1200&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;ГОСТ 10884-94&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_10884_94 {
            get {
                return ResourceManager.GetString("ГОСТ_10884_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;50&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;19903-2015&quot;
        ///	DocName=&quot;Прокат листовой горячекатанный. Сортамент&quot;
        ///	DocNameShort=&quot;Прокат листовой&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Лист&quot;
        ///	Size=&quot;BxHxL&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Листы&quot;
        ///	Image=&quot;List&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[B]x[H] [DocType] [DocNum]&quot;
        ///	CMass=&quot;7850&quot;
        ///  MeType=&quot;13,B,H,L&quot;
        ///&gt;
        ///&lt;/Document&gt;.
        /// </summary>
        internal static string ГОСТ_19903_2015 {
            get {
                return ResourceManager.GetString("ГОСТ_19903_2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;49&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;2590-2006&quot;
        ///	DocName=&quot;Прокат сортовой стальной горячекатаный круглый&quot;
        ///	DocNameShort=&quot;Прокат круглый&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Круг&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 2590-2006&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop3&quot;
        ///	SymbolSum=&quot;3&quot;
        ///	MeType=&quot;3,Prop1,L&quot;
        ///	Symbol1=&quot;Диаметр, мм&quot; Symbol2=&quot;Площадь сечения, см^2&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_2590_2006 {
            get {
                return ResourceManager.GetString("ГОСТ_2590_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;48&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;2591-2006&quot;
        ///	DocName=&quot;Прокат стальной горячекатаный квадратный. Сортамент&quot;
        ///	DocNameShort=&quot;Прокат квадратный&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Прокат&quot;
        ///	ItemType1=&quot;Класс по точности$Б$В&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 2591-88&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [ItemType1]  [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop4&quot;
        ///	SymbolSum=&quot;4&quot;
        ///	MeType=&quot;4,Prop2,L&quot;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_2591_2006 {
            get {
                return ResourceManager.GetString("ГОСТ_2591_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;47&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;26020-83&quot;
        ///	DocName=&quot;Двутавры стальные горячекатанные с параллельными гранями полок&quot;
        ///	DocNameShort=&quot;Двутавры нормальные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 26020-83&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	MeType=&quot;12,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;
        ///	SymbolSum=&quot;15&quot;
        ///	Symbo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_26020_83_1 {
            get {
                return ResourceManager.GetString("ГОСТ_26020_83_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;46&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;26020-83&quot;
        ///	DocName=&quot;Двутавры стальные горячекатанные с параллельными гранями полок&quot;
        ///	DocNameShort=&quot;Двутавры широкополочные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 26020-83&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	MeType=&quot;12,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;
        ///	SymbolSum=&quot;15&quot;
        ///	S [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_26020_83_2 {
            get {
                return ResourceManager.GetString("ГОСТ_26020_83_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;45&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;26020-83&quot;
        ///	DocName=&quot;Двутавры стальные горячекатанные с параллельными гранями полок&quot;
        ///	DocNameShort=&quot;Двутавры колонные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 26020-83&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	MeType=&quot;12,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;
        ///	SymbolSum=&quot;15&quot;
        ///	Symbol1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_26020_83_3 {
            get {
                return ResourceManager.GetString("ГОСТ_26020_83_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;44&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;26020-83&quot;
        ///	DocName=&quot;Двутавры стальные горячекатанные с параллельными гранями полок&quot;
        ///	DocNameShort=&quot;Двутавры дополнительной серии (Д)&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 26020-83&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	MeType=&quot;12,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;
        ///	SymbolSu [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_26020_83_4 {
            get {
                return ResourceManager.GetString("ГОСТ_26020_83_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;43&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;30245-2003&quot;
        ///	DocName=&quot;Профили стальные гнутые замкнутые сварные квадратные и прямоугольные для строительных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Профиль квадратный&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Профиль&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Профили&quot;
        ///	Image=&quot;ГОСТ 30245-2003_1&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;6 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_30245_2003_1 {
            get {
                return ResourceManager.GetString("ГОСТ_30245_2003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;42&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;30245-2003&quot;
        ///	DocName=&quot;Профили стальные гнутые замкнутые сварные квадратные и прямоугольные для строительных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Профиль прямоугольный&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Профиль&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Профили&quot;
        ///	Image=&quot;ГОСТ 30245-2003_2&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop12&quot;
        ///	MeTyp [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_30245_2003_2 {
            get {
                return ResourceManager.GetString("ГОСТ_30245_2003_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;41&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;5781-82&quot;
        ///	DocName=&quot;Сталь горячекатаная для армирования железобетонных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматурной стали$A-I$A-II$A-III$A-IV$A-V$A-VI&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;ГОСТ 5781-82&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1]-[ItemType1] [DocType] [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_5781_82 {
            get {
                return ResourceManager.GetString("ГОСТ_5781_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;40&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;6009-74 &quot;
        ///	DocName=&quot;Лента стальная горячекатанная. Технические условия&quot;
        ///	DocNameShort=&quot;Лента стальная&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Лента&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;List&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1]x[Prop2]  [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop3&quot;
        ///  MeType=&quot;13,Prop1,Prop2,L&quot;
        ///	SymbolSum=&quot;3&quot;
        ///	Symbol1=&quot;Ширина, мм&quot; Symbol2=&quot;Толщина, мм&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_6009_74 {
            get {
                return ResourceManager.GetString("ГОСТ_6009_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;39&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;6727-80&quot;
        ///	DocName=&quot;Проволока из низкоуглеродистой стали холоднотянутая для армирования железобетонных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Проволока&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Проволока&quot;
        ///	ItemType1=&quot;Класс арматурной стали$BpI&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;ГОСТ 6727-80&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName] [Prop1]  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_6727_80 {
            get {
                return ResourceManager.GetString("ГОСТ_6727_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;38&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;82-70&quot;
        ///	DocName=&quot;Прокат стальной горячекатаный широкополосный универсальный. Сортамент&quot;
        ///	DocNameShort=&quot;Полоса&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Полоса&quot;
        ///	ItemType1=&quot;Класс по ребровой кривизне$А$Б&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;List&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ItemType1][Prop2]x[Prop1]  [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop3&quot;
        ///  MeType=&quot;13,Prop1,Prop2,L [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_82_70 {
            get {
                return ResourceManager.GetString("ГОСТ_82_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;37&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8239-89&quot;
        ///	DocName=&quot;Двутавры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Двутавры&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8239-89&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;11,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,L&quot;
        ///	SymbolSum=&quot;16&quot;
        ///	Symbol1=&quot;Номер двутавра&quot; Symbol2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8239_89 {
            get {
                return ResourceManager.GetString("ГОСТ_8239_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;36&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8240-97&quot;
        ///	DocName=&quot;Швеллеры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Швеллеры с уклоном внутренних граней полок&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Швеллер&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8240-97_1&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;8,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,L&quot;
        ///	SymbolSum=&quot;17&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8240_97_1 {
            get {
                return ResourceManager.GetString("ГОСТ_8240_97_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;35&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8240-97&quot;
        ///	DocName=&quot;Швеллеры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Швеллеры с параллельными гранями полок&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Швеллер&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8240-97_2&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;10,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,L&quot;
        ///	SymbolSum=&quot;17&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8240_97_2 {
            get {
                return ResourceManager.GetString("ГОСТ_8240_97_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;34&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8240-97&quot;
        ///	DocName=&quot;Швеллеры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Швеллеры экономичные с параллельными гранями полок&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Швеллер&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8240-97_2&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;10,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,L&quot;
        ///	xMark [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8240_97_3 {
            get {
                return ResourceManager.GetString("ГОСТ_8240_97_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;33&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8240-97&quot;
        ///	DocName=&quot;Швеллеры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Швеллеры легкой серии с параллельными гранями полок&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Швеллер&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8240-97_2&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;10,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,L&quot;
        ///	Symb [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8240_97_4 {
            get {
                return ResourceManager.GetString("ГОСТ_8240_97_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;32&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8240-97&quot;
        ///	DocName=&quot;Швеллеры стальные горячекатаные. Сортамент&quot;
        ///	DocNameShort=&quot;Швеллеры специальные&quot;
        ///DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Швеллер&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8240-97_2&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[№][Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop9&quot;
        ///	MeType=&quot;9,Prop2,Prop3,Prop4,Prop5,Prop6,Prop7,Prop8,L&quot;
        ///	SymbolSum=&quot;17&quot;
        ///	Symbol1=&quot;Номер  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8240_97_5 {
            get {
                return ResourceManager.GetString("ГОСТ_8240_97_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;31&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8509-93&quot;
        ///	DocName=&quot;Уголки стальные горячекатаные равнополочные. Сортамент&quot;
        ///	DocNameShort=&quot;Уголки равнополочные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Уголок&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8509-93&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop2]x[Prop3] [DocType] [DocNum]&quot;
        ///	HasMassRule=&quot;true&quot;
        ///	WMass=&quot;Prop17&quot;
        ///	SymbolSum=&quot;17&quot;
        ///	MeType=&quot;1,Prop2,Prop3,Prop4,Prop5, [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8509_93 {
            get {
                return ResourceManager.GetString("ГОСТ_8509_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;30&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8510-86&quot;
        ///	DocName=&quot;Уголки стальные горячекатаные неравнополочные. Сортамент&quot;
        ///	DocNameShort=&quot;Уголки неравнополочные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Уголок&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;ГОСТ 8510-86&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop2]x[Prop3]x[Prop4] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop21&quot;
        ///	SymbolSum=&quot;21&quot;
        ///	MeType=&quot;2,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8510_86 {
            get {
                return ResourceManager.GetString("ГОСТ_8510_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;29&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8568-77&quot;
        ///	DocName=&quot;Листы стальные с ромбическим и чечевичным рифлением. Технические условия&quot;
        ///	DocNameShort=&quot;Листы стальные с ромбическим рифл.&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;ромб&quot;
        ///	ItemType1=&quot;Тип изготовления$Лист$Рулон&quot;
        ///	Size=&quot;BxL&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Листы&quot;
        ///	Image=&quot;ГОСТ 8568-77_1&quot;
        ///	HasSteel=&quot;false&quot;
        ///	DimType=&quot;м.кв.&quot;
        ///	Rule=&quot;[ItemType1] [ShortName] [Prop1]x[BxL] [DocType] [DocNum]&quot;
        ///	SMass=&quot;Prop4&quot;
        ///	S [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8568_77_1 {
            get {
                return ResourceManager.GetString("ГОСТ_8568_77_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;28&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8568-77&quot;
        ///	DocName=&quot;Листы стальные с ромбическим и чечевичным рифлением. Технические условия&quot;
        ///	DocNameShort=&quot;Листы стальные с чечевичным рифл.&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;чечевица&quot;
        ///	ItemType1=&quot;Тип изготовления$Лист$Рулон&quot;
        ///	Size=&quot;BxL&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Листы&quot;
        ///	Image=&quot;ГОСТ 8568-77_2&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;false&quot;
        ///	DimType=&quot;м.кв.&quot;
        ///	Rule=&quot;[ItemType1] [ShortName] [Prop1]x[BxL]  [DocType] [D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8568_77_2 {
            get {
                return ResourceManager.GetString("ГОСТ_8568_77_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;27&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8639-82&quot;
        ///	DocName=&quot;Трубы стальные квадратные&quot;
        ///	DocNameShort=&quot;Трубы квадратные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Профили&quot;
        ///	Image=&quot;ГОСТ 8639-82&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop5&quot;
        ///	MeType=&quot;7,Prop2,Prop3,L&quot;
        ///	SymbolSum=&quot;7&quot;
        ///	Symbol1=&quot;Марка&quot;
        ///	Symbol2=&quot;А, мм&quot;
        ///	Symbol3=&quot;S, мм&quot;
        ///	Symbol4=&quot;S, см^2&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8639_82 {
            get {
                return ResourceManager.GetString("ГОСТ_8639_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;26&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8645-68&quot;
        ///	DocName=&quot;Трубы стальные прямоугольные&quot;
        ///	DocNameShort=&quot;Трубы прямоугольные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Профили&quot;
        ///	Image=&quot;ГОСТ 8645-68&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop6&quot;
        ///	MeType=&quot;6,Prop2,Prop3,Prop4,L&quot;
        ///	SymbolSum=&quot;10&quot;
        ///	Symbol1=&quot;Марка&quot;
        ///	Symbol2=&quot;А, мм&quot;
        ///	Symbol3=&quot;В, мм&quot;
        ///	Symb [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8645_68 {
            get {
                return ResourceManager.GetString("ГОСТ_8645_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;25&quot;
        ///	DocType=&quot;ГОСТ&quot;
        ///	DocNum=&quot;8732-78&quot;
        ///	DocName=&quot;Трубы стальные бесшовные горячедеформированные. Сортамент&quot;
        ///	DocNameShort=&quot;Трубы стальные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Трубы&quot;
        ///	Image=&quot;Tube&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop4&quot;
        ///	SymbolSum=&quot;4&quot;
        ///	MeType=&quot;5,Prop2,Prop3,L&quot;
        ///	Symbol1=&quot;Марка&quot;
        ///	Symbol2=&quot;Наружный диаметр, мм&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_8732_78 {
            get {
                return ResourceManager.GetString("ГОСТ_8732_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;24&quot;
        ///	DocType=&quot;ГОСТ Р&quot;
        ///	DocNum=&quot;52544-2006&quot;
        ///	DocName=&quot;Прокат арматурный свариваемый периодического профиля классов А500С и В500С для армирования железобетонных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс$А500С$В500С&quot;
        ///  ItemType2=&quot;Вид продукции$Пруток$Моток&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;ГОСТ Р 52544-2006&quot;
        ///	HasSteel=&quot;false&quot;
        ///	DimTyp [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ГОСТ_Р_52544_2006 {
            get {
                return ResourceManager.GetString("ГОСТ_Р_52544_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;23&quot;
        ///	DocType=&quot;ДСТУ&quot;
        ///	DocNum=&quot;3760:2006&quot;
        ///	DocName=&quot;Прокат арматурный для железобетонных изделий. Технические условия&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматуры$А240С$А400С$А500С$А600$А600С$А600К$А800К$А800СК$А1000&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;ДСТУ 3760_2006&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [ItemType1] [DocTy [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ДСТУ_3760_2006 {
            get {
                return ResourceManager.GetString("ДСТУ_3760_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;22&quot;
        ///	DocType=&quot;СТБ&quot;
        ///	DocNum=&quot;1704-2006&quot;
        ///	DocName=&quot;Арматура ненапрягаемая для железобетонных конструкций. Технические условия&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматуры$S240$S400$S500&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;СТБ 1704-2006&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [ItemType1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop6&quot;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string СТБ_1704_2006 {
            get {
                return ResourceManager.GetString("СТБ_1704_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;21&quot;
        ///	DocType=&quot;СТО АСЧМ&quot;
        ///	DocNum=&quot;20-93&quot;
        ///	DocName=&quot;Двутавры горячекатаные с параллельными гранями полок. Технические условия.&quot;
        ///	DocNameShort=&quot;Двутавры&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Двутавр&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Прокат&quot;
        ///	Image=&quot;СТО АСЧМ 20-93&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	MeType=&quot;12,Prop2,Prop3,Prop4,Prop5,Prop6,L&quot;
        ///	SymbolSum=&quot;15&quot;
        ///	Symbo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string СТО_АСЧМ_20_93 {
            get {
                return ResourceManager.GetString("СТО_АСЧМ_20_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;20&quot;
        ///	DocType=&quot;СТО АСЧМ&quot;
        ///	DocNum=&quot;7-93&quot;
        ///	DocName=&quot;Прокат периодического профиля из арматурной стали&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматуры$А400С$А500С$А600С&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;СТО АСЧМ 7-93&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1]-[ItemType1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop3&quot;
        ///	SymbolSum=&quot;3&quot;
        ///	MeType [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string СТО_АСЧМ_7_93 {
            get {
                return ResourceManager.GetString("СТО_АСЧМ_7_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;19&quot;
        ///	DocType=&quot;СТО АСЧМ&quot;
        ///	DocNum=&quot;8-93&quot;
        ///	DocName=&quot;Прокат круглого гладкого профиля из арматурной стали&quot;
        ///	DocNameShort=&quot;Арматура&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Арматура&quot;
        ///	ItemType1=&quot;Класс арматуры$А240С$А300С&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Арматура/проволока&quot;
        ///	Image=&quot;нет&quot;
        ///	HasSteel=&quot;false&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[Prop1]-[ItemType1] [DocType] [DocNum]&quot;
        ///	WMass=&quot;Prop3&quot;
        ///	SymbolSum=&quot;3&quot;
        ///	MeType=&quot;3,Prop1,L&quot;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string СТО_АСЧМ_8_93 {
            get {
                return ResourceManager.GetString("СТО_АСЧМ_8_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///	Id=&quot;60&quot;
        ///	DocType=&quot;ТУ&quot;
        ///	DocNum=&quot;14-3Р-56-2001&quot;
        ///	DocName=&quot;Трубы стальные сварные диаметром 1420, 1620, 1720, 2020 и 2220 мм общего назначения&quot;
        ///	DocNameShort=&quot;Трубы стальные&quot;
        ///  DocStatus=&quot;True&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Трубы&quot;
        ///	ItemType1=&quot;Марка стали$Ст2кп$Ст2пс$Ст2сп$Ст3кп$Ст3пс$Ст3сп$Ст3пс3$Ст3сп3$Ст3пс4$Ст3сп4&quot;
        ///	Size=&quot;L&quot;
        ///	Image=&quot;Tube&quot;
        ///	HasSteel=&quot;false&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName] [Prop1]x[Prop2]-[ItemType1]-[D [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ТУ_14_3Р_56_2001 {
            get {
                return ResourceManager.GetString("ТУ_14_3Р_56_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Document
        ///  Id=&quot;18&quot;
        ///	DocType=&quot;ТУ&quot;
        ///	DocNum=&quot;36-2287-80&quot;
        ///	DocName=&quot;Профили гнутые замкнутые сварные квадратные и прямоугольные&quot;
        ///	DocNameShort=&quot;Трубы стальные&quot;
        ///  DocStatus=&quot;False&quot;
        ///	ShortName=&quot;Труба&quot;
        ///	Size=&quot;L&quot;
        ///	MainGroup=&quot;Металл&quot;
        ///	Group=&quot;Профили&quot;
        ///	Image=&quot;ТУ 36-2287-80&quot;
        ///	HasSteel=&quot;true&quot;
        ///	HasDimension=&quot;true&quot;
        ///	DimType=&quot;Длина,п.м&quot;
        ///	Rule=&quot;[ShortName] [Prop1] [DocType] [DocNum]&quot;
        ///  MeType=&quot;6,Prop2,Prop2,Prop3,L&quot;
        ///	WMass=&quot;Prop8&quot;
        ///	SymbolSum=&quot;8&quot;
        ///	Symbol1=&quot;Марка&quot; S [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ТУ_36_2287_80 {
            get {
                return ResourceManager.GetString("ТУ_36_2287_80", resourceCulture);
            }
        }
    }
}
